### ISSUE TITLE
Error starting docker: Exception creating secured server socket : parseAlgParameters failed: ObjectIdentifier() -- data isn't an object ID (tag = 48)

### ISSUE THREAD

**Issue by RensOliemans** [kran0/davmail-docker#1]
Hi, I've been struggling with an error related to Davmail SSL and found a solution, but since others might find the same error I thought I'd document it here.

I'm using docker-compose, pretty much like the sample, but with the relevant SSL settings. For good measure, here it is completely (albeit with a default password `password`):

    #!/usr/bin/env -S docker-compose -f

    services:
      davmail:
        image: kran0/davmail-docker:latest

        environment:
          - DAVMAIL_SERVER=true
          - DAVMAIL_URL=https://outlook.office365.com/EWS/Exchange.asmx  # Not sure if this is needed
          - DAVMAIL_CALDAVPORT=1080
          - DAVMAIL_IMAPPORT=1143
          - DAVMAIL_LDAPPORT=1389
          - DAVMAIL_POPPORT=1110
          - DAVMAIL_SMTPPORT=1025
          - DAVMAIL_ALLOWREMOTE=true
          - DAVMAIL_DISABLEUPDATECHECK=true
          - DAVMAIL_LOGFILEPATH=/dev/stdout
          - DAVMAIL_SSL_KEYSTORETYPE=PKCS12
          - DAVMAIL_SSL_KEYSTOREFILE=/etc/davmail/davmail.p12
          - DAVMAIL_SSL_KEYSTOREPASS=password
          - DAVMAIL_SSL_KEYPASS=password
        ports:
          - 1080:1080
          - 1143:1143
          - 1389:1389
          - 1110:1110
          - 1025:1025
        volumes:
          - /mnt/apps/davmail:/etc/davmail
        restart: on-failure

Note the volume `mnt/apps/davmail:/etc/davmail`, and the Docker environment setting `DAVMAIL_SSL_KEYSTOREFILE`. If you get a similar but different error, where it complains about a missing davmail.p12 file, make sure that you put the correct file in the correct spot, and ensure that Docker can read it. Please ensure that it isn't globally readable though!

Anyhow, back to my error. I generated the `davmail.p12` according to the excellent [davmail docs](https://davmail.sourceforge.net/sslsetup.html). `keytool` wasn't installed on my machine, so I installed `openjdk-18-jre-headless` (Debian), which includes it.

When starting the Docker container, I got the following output: 

    $ docker-compose --env-file .env up                                                                                   
    Recreating davmail_davmail_1 ... done                                                                                 
    Attaching to davmail_davmail_1                                                                                        
    davmail_1  | 2022-10-13 15:28:38,363 ERROR [main] davmail  - Unable to bind server socket for SMTP on port 1025: Exception creating secured server socket : parseAlgParameters failed: ObjectIdentifier() -- data isn't an object ID (tag = 4
    8)Unable to bind server socket for POP on port 1110: Exception creating secured server socket : parseAlgParameters failed: ObjectIdentifier() -- data isn't an object ID (tag = 48)Unable to bind server socket for IMAP on port 1143: Except
    ion creating secured server socket : parseAlgParameters failed: ObjectIdentifier() -- data isn't an object ID (tag = 48)Unable to bind server socket for CALDAV on port 1080: Exception creating secured server socket : parseAlgParameters f
    ailed: ObjectIdentifier() -- data isn't an object ID (tag = 48)Unable to bind server socket for LDAP on port 1389: Exception creating secured server socket : parseAlgParameters failed: ObjectIdentifier() -- data isn't an object ID (tag =
     48)                    

[This SO answer](https://stackoverflow.com/questions/69749925/java-lang-illegalargumentexception-parsealgparameters-failed-objectidentifier) by Bashir Onuche Okala III pointed me to the correct spot: I used the wrong JDK version! I installed `openjdk-18-jre-headless`, **it should be** `openjdk-8-jre-headless`. See the [Dockerfile in this repo](https://github.com/kran0/davmail-docker/blob/master/Dockerfile#L1) where it uses OpenJDK 8.

**Comment by RensOliemans** [comment]
Also, I found that `msmtp` doesn't allow for self-signed certificates. The davmail docs come to the rescue again, showing you that you can convert a signed certificate to PKCS12 format. However, my `openssl` would only generate a suitable PKCS12 file with the `-legacy` flag, so you'll have to keep that in mind! Another option would be to use a different keyStoreType, such as JKS, but I haven't looked into that yet.

**Comment by RensOliemans** [comment]
@kran0 I hope that you're ok with me hijacking the Issues tab for some documentation, I could add this to the README.md, or a wiki tag if you prefer.

**Comment by kran0** [comment]
@RensOliemans , thank you for your issue and the solition.

I will watch deep in it:
1. Thinking about move to jdk 17lts as the bilder and jre 17 as the runtime. It must work. 
2. Use this setting in Tests.
3. Or just add as an example.
4. As far as i know, JKS is not better tan PKCS12 at all. And it also have compatibility issues between Java versions and even architectures. 

For long time i used to use cert hash saved as string in properties file. Your solition looks mich better. And the keystore container may be provided with ConfigMap setting and so on. 

You will make me a favour by crating wiki Page with your configuration example. Thank you a lot.

**Comment by RensOliemans** [comment]
I will write a wiki page! But, I cannot create or edit Wiki pages of someone else's repo, and pull requests do not work for GitHub wiki's I am afraid... [SO question: How to pull request a wiki page on GitHub?](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github)

I think that I will just create a wiki page on my own repo, and attach the Markdown file in a comment here.

**Comment by RensOliemans** [comment]
I added a wiki page [here](https://github.com/RensOliemans/davmail-docker/wiki/Setting-up-SSL). I am not sure what the best way is to copy this to your own wiki page, but you can clone my wiki repo using this [clone url](https://github.com/RensOliemans/davmail-docker.wiki.git), and that contains the `Setting-up-SSL.md` file.

If anything is unclear I'll be happy to help, but I am afraid that the coming weeks are a bit busy for me.

**Comment by kran0** [comment]
[b61fe30](https://github.com/kran0/davmail-docker/wiki/Setting-up-SSL/b61fe301c55a4f167be1e15fd1b45b299f1dc973)

Thank you, @RensOliemans
